language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
before_script:
  - npm prune
script:
  - npm run test:coverage
  - npm run coverage:check
after_success:
  - npm run coverage:report
  - npm run semantic-release
branches:
  only:
    - master
